# Netlify Configuration for VitaSyn Labs

[build]
  functions = "netlify/functions"
  publish = "."

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (set these in Netlify dashboard)
# DATABASE_URL = your_neon_connection_string
# JWT_SECRET = your_random_secret_key